server:
  undertow:
    threads:
      io: 16
      worker: 2000
    buffer-size: 1024
    direct-buffers: true
    accesslog:
      dir: /lsx/log/
      enabled: true
      prefix: web.
  port: 8312


# spring 配置
spring:
  # redis 配置
  redis:
    host: localhost
    port: 6379
    database: 2
    password:
    timeout: 10s
    lettuce:
      pool:
        min-idle: 0
        max-active: 8
        max-wait: -1ms
        max-idle: 8
  jackson:
    serialization:
      indent-output: true
  autoconfigure:
    exclude: com.alibaba.druid.spring.boot.autoconfigure.DruidDataSourceAutoConfigure
  datasource:
    dynamic:
      primary: local
      datasource:
        # 本地mysql
        local:
          driverClassName: com.mysql.cj.jdbc.Driver
          url: jdbc:mysql://192.168.10.87:3306/local?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
          username: root
          password: 11098319
        # 虚拟机mysql
      #        centos:
      #          driverClassName: com.mysql.cj.jdbc.Driver
      #          url: jdbc:mysql://192.168.10.142:3306/djwk_test?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
      #          username: root
      #          password: xiAtiAn@djwk
      druid:
        # 初始连接数
        initialSize: 5
        # 最小连接池数量
        minIdle: 10
        # 最大连接池数量
        maxActive: 20
        # 配置获取连接等待超时的时间
        maxWait: 60000
        # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
        timeBetweenEvictionRunsMillis: 60000
        # 配置一个连接在池中最小生存的时间，单位是毫秒
        minEvictableIdleTimeMillis: 300000
        # 配置一个连接在池中最大生存的时间，单位是毫秒
        maxEvictableIdleTimeMillis: 900000
        # 配置检测连接是否有效
        validationQuery: SELECT 1 FROM DUAL
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        webStatFilter:
          enabled: true
        filter:
          stat:
            enabled: true
            # 慢SQL记录
            log-slow-sql: true
            slow-sql-millis: 1000
            merge-sql: true
          wall:
            config:
              multi-statement-allow: true


# 日志配置
logging:
  level:
    com.example: debug
    org.springframework: warn